service: hello-express-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  versionFunctions: false

custom:
  prune:
    automatic: true
    number: 1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'


plugins:
  - serverless-offline
  - serverless-prune-plugin